# Generated by Django 4.2.13 on 2024-05-25 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_type", models.CharField(max_length=100)),
                ("contract_abbreviation", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100)),
                (
                    "department_abbreviation",
                    models.CharField(max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                            ("Prof", "Prof"),
                            ("Eng", "Eng"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100, null=True)),
                ("position", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("FIN", "Finance"),
                            ("IT", "Information Technology"),
                            ("SALES", "Sales"),
                            ("MARK", "Marketing"),
                            ("PROD", "Production"),
                            ("LOG", "Logistics"),
                            ("ADM", "Administration"),
                            ("MNG", "Management"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Time"),
                            ("PART", "Part Time"),
                            ("ATT", "Attachment"),
                            ("CON", "Contract"),
                            ("INT", "Internship"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_picture"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_name", models.CharField(max_length=100)),
                ("title_abbreviation", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company_account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("password1", models.CharField(default="", max_length=100)),
                ("password2", models.CharField(default="", max_length=100)),
                ("company_address", models.CharField(max_length=100)),
                ("company_email", models.EmailField(max_length=100)),
                ("company_phone", models.CharField(max_length=100)),
                ("company_website", models.URLField(max_length=100)),
                (
                    "company_logo",
                    models.ImageField(default="default.jpg", upload_to="company_logo"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
