# Generated by Django 4.2.13 on 2024-05-22 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_address", models.CharField(max_length=100)),
                ("company_email", models.EmailField(max_length=100)),
                ("company_phone", models.CharField(max_length=100)),
                ("company_website", models.URLField(max_length=100)),
                (
                    "company_logo",
                    models.ImageField(default="default.jpg", upload_to="company_logo"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
