# Generated by Django 4.2.13 on 2024-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_account",
            name="password1",
            field=models.CharField(default="password", max_length=100),
        ),
        migrations.AddField(
            model_name="company_account",
            name="password2",
            field=models.CharField(default="password", max_length=100),
        ),
    ]
