# Generated by Django 4.2.13 on 2024-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="contract_type",
            name="company",
        ),
        migrations.RemoveField(
            model_name="department",
            name="company",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="company",
        ),
        migrations.RemoveField(
            model_name="title",
            name="company",
        ),
    ]
