# Generated by Django 4.2.13 on 2024-05-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_account_password1_company_account_password2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company_account",
            name="user",
        ),
    ]
