# Generated by Django 4.2.13 on 2024-05-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_alter_company_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
            ),
        ),
    ]
