# Generated by Django 4.2.13 on 2024-06-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_employee_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="shift",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
