# Generated by Django 4.2.13 on 2024-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_company_account_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                (
                    "logo",
                    models.ImageField(default="default.jpg", upload_to="company_logo"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="contract_type",
            old_name="contract_abbreviation",
            new_name="abbreviation",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="department_abbreviation",
            new_name="abbreviation",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="department_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="title",
            old_name="title_abbreviation",
            new_name="abbreviation",
        ),
        migrations.RenameField(
            model_name="title",
            old_name="title_name",
            new_name="name",
        ),
        migrations.DeleteModel(
            name="Company_account",
        ),
    ]
