# Generated by Django 4.2.13 on 2024-05-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_company_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
