# Generated by Django 4.2.13 on 2024-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_company_account_password1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="contract_types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_type", models.CharField(max_length=100)),
                ("contract_description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100)),
                ("department_description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                            ("Prof", "Prof"),
                            ("Eng", "Eng"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("FIN", "Finance"),
                            ("IT", "Information Technology"),
                            ("SALES", "Sales"),
                            ("MARK", "Marketing"),
                            ("PROD", "Production"),
                            ("LOG", "Logistics"),
                            ("ADM", "Administration"),
                            ("MNG", "Management"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Time"),
                            ("PART", "Part Time"),
                            ("ATT", "Attachment"),
                            ("CON", "Contract"),
                            ("INT", "Internship"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_picture"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="titles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_name", models.CharField(max_length=100)),
                ("title_description", models.CharField(max_length=100)),
            ],
        ),
    ]
