# Generated by Django 4.2.13 on 2024-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_contract_types_departments_employee_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_type", models.CharField(max_length=100)),
                ("contract_abbreviation", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100)),
                (
                    "department_abbreviation",
                    models.CharField(max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_name", models.CharField(max_length=100)),
                ("title_abbreviation", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="contract_types",
        ),
        migrations.DeleteModel(
            name="departments",
        ),
        migrations.DeleteModel(
            name="titles",
        ),
    ]
