# Generated by Django 4.2.13 on 2024-05-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_company_account_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company_account",
            name="user",
        ),
    ]
