# Generated by Django 5.0.6 on 2024-05-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_staff_employee_alter_company_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='companyname',
        ),
    ]
