# Generated by Django 5.0.6 on 2024-05-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_name_company_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='companyid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='company',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='employeepassword',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='employeeusername',
        ),
    ]
